"""separate paid status

Revision ID: a200f219eeb7
Revises: be78747aa40d
Create Date: 2024-09-21 20:22:30.557725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages.integrations.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'a200f219eeb7'
down_revision: Union[str, None] = 'be78747aa40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paid', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('orders', 'status',
                    existing_type=sa.VARCHAR(length=10),
                    type_=sa.Enum('waiting', 'done', name='orderstatus'),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
                    existing_type=sa.Enum('waiting', 'done', name='orderstatus'),
                    type_=sa.VARCHAR(length=10),
                    existing_nullable=True)
    op.drop_column('orders', 'paid')
    # ### end Alembic commands ###
