"""allow selling out of items

Revision ID: be78747aa40d
Revises: d696e4bcb7a6
Create Date: 2024-09-19 20:30:11.798746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages.integrations.sqlalchemy



# revision identifiers, used by Alembic.
revision: str = 'be78747aa40d'
down_revision: Union[str, None] = 'd696e4bcb7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemtypes', sa.Column('soldOut', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemtypes', 'soldOut')
    # ### end Alembic commands ###
