"""allow adding name to on-site ordering

Revision ID: d696e4bcb7a6
Revises: 396973d72e89
Create Date: 2024-09-18 19:57:23.373340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages.integrations.sqlalchemy



# revision identifiers, used by Alembic.
revision: str = 'd696e4bcb7a6'
down_revision: Union[str, None] = '396973d72e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('onSiteName', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'onSiteName')
    # ### end Alembic commands ###
