"""options selling out

Revision ID: e96cea0c373d
Revises: 3093b75b15a7
Create Date: 2024-09-23 15:16:45.032346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages.integrations.sqlalchemy



# revision identifiers, used by Alembic.
revision: str = 'e96cea0c373d'
down_revision: Union[str, None] = '3093b75b15a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optionitems', sa.Column('soldOut', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('optionitems', 'soldOut')
    # ### end Alembic commands ###
